from io import BytesIO

import numpy as np
import pytest

from gvc.bitstream import BitstreamReader
from gvc.data_structures import ParameterSet, RowColIds, VectorAMax
from gvc.data_structures.consts import BinarizationID, CodecID, DataUnitType
from gvc.data_structures.data_unit import DataUnitHeader


# These bytes are produced by the original tnt-LUH/gvc v1 serialization layout.
# They are intentionally constants, not regenerated by the implementation under
# test, so an encoder+decoder change cannot silently move the file format.
V1_PARAMETER_SET_GOLDEN = bytes.fromhex("000000000b0380402906c0")
V1_ROW_IDS_GOLDEN = bytes.fromhex("8d")
V1_AMAX_GOLDEN = bytes.fromhex("000000050344e8")


def _golden_parameter_set():
    return ParameterSet(
        parameter_set_id=3,
        any_missing_flag=True,
        not_available_flag=False,
        p=2,
        binarization_id=BinarizationID.BIT_PLANE,
        num_bin_mat=2,
        concat_axis=2,
        sort_variants_row_flags=[True, False],
        sort_variants_col_flags=[False, True],
        transpose_variants_mat_flags=[False, True],
        variants_coder_ids=[CodecID.JBIG1, CodecID.GABAC],
        encode_phase_data=False,
        phase_value=True,
    )


def test_parameter_set_matches_v1_golden_bytes():
    assert _golden_parameter_set().to_bytes() == V1_PARAMETER_SET_GOLDEN


def test_v1_parameter_set_golden_bytes_are_still_decodable():
    reader = BitstreamReader(BytesIO(V1_PARAMETER_SET_GOLDEN))
    data_unit_type = reader.read_bytes(1, ret_int=True)
    assert data_unit_type == DataUnitType.PARAMETER_SET

    header = DataUnitHeader.from_bitstream(data_unit_type, reader)
    restored = ParameterSet.from_bitstream(reader, header)

    assert restored.parameter_set_id == 3
    assert restored.any_missing_flag is True
    assert restored.not_available_flag is False
    assert restored.p == 2
    assert restored.binarization_id == BinarizationID.BIT_PLANE
    assert restored.num_bin_mat == 2
    assert restored.concat_axis == 2
    assert restored.sort_variants_row_flags == [True, False]
    assert restored.sort_variants_col_flags == [False, True]
    assert restored.transpose_variants_mat_flags == [False, True]
    assert restored.variants_coder_ids == [CodecID.JBIG1, CodecID.GABAC]
    assert restored.encode_phase_data is False
    assert restored.phase_value is True


def test_v1_permutation_golden_bytes():
    ids = np.array([2, 0, 3, 1], dtype=np.uint16)
    assert RowColIds(ids).to_bytes() == V1_ROW_IDS_GOLDEN
    np.testing.assert_array_equal(
        RowColIds.from_bytes(V1_ROW_IDS_GOLDEN, len(ids)).ids,
        ids,
    )


def test_v1_amax_golden_bytes():
    values = np.array([1, 2, 3, 7, 1], dtype=np.uint16)
    encoded = VectorAMax(values).to_bitio().to_bytes(align=True)
    assert encoded == V1_AMAX_GOLDEN
    np.testing.assert_array_equal(VectorAMax.from_bytes(encoded).vector, values)


def test_parameter_set_detects_corrupted_declared_length():
    corrupted = bytearray(V1_PARAMETER_SET_GOLDEN)
    corrupted[4] += 1

    reader = BitstreamReader(BytesIO(corrupted))
    data_unit_type = reader.read_bytes(1, ret_int=True)
    header = DataUnitHeader.from_bitstream(data_unit_type, reader)

    with pytest.raises(ValueError, match="length mismatch"):
        ParameterSet.from_bitstream(reader, header)
