from enum import IntEnum

class DataUnitType(IntEnum):
    PARAMETER_SET = 0
    ACCESS_UNIT = 1

class ContentID(IntEnum):
    GENOTYPE = 0

class ConcatAxis(IntEnum):
    ROW = 0
    COL = 1
    NONE = 2
    TOTAL = 3

class BinarizationFlag(IntEnum):
    BIT_PLANE = 0
    ROW_SPLIT = 1
    RC_BIN_SPLIT = 2
    RC_BIN_SPLIT2 = 3

class CodecID(IntEnum):
    JBIG1 = 0
    GABAC = 1
    PPMD = 2 #? Temporary

BYTEORDER = 'big'
DATA_UNIT_TYPE_LEN = 1
DATA_UNIT_SIZE_LEN = 4

###? Parameter Set
PARAMETER_SET_ID_LEN = 1
ANY_MISSING_FLAG_BITLEN = 1
NOT_AVAILABLE_FLAG_BITLEN = 1
P_BITLEN = 8
BINARIZATION_BITLEN = 2
NUM_BIN_MAT_BITLEN = 8
CONCAT_AXIS_BITLEN = 2
ENCODE_PHASE_DATA_BITLEN = 1
SORT_VARIANTS_FLAG_BITLEN = 1
TRANSPOSE_FLAG_BITLEN = 1
PHASE_VALUE_BITLEN = 1
CODER_ID_BITLEN = 2

###? GT Payload
VARIANTS_PAYLOAD_SIZES_LEN = 4
VARIANTS_AMAX_PAYLOAD_SIZE_LEN = 4
PHASE_PAYLOAD_SIZE_LEN = 4
ROW_IDS_SIZE_LEN = 4
COL_IDS_SIZE_LEN = 4

###? AMAX Vector
AMAX_NUM_ENTRIES_LEN = 4
AMAX_BITS_PER_ENTRY_LEN = 1
AMAX_FLAG_BITLEN = 1

###? Block
CONTENT_ID_LEN = 1
BLOCK_PAYLOAD_SIZE_LEN = 4

###? Access Unit
ACCESS_UNIT_ID_LEN = 4
NUM_BLOCKS_LEN = 1

###? Serialized Matrix
NROW_LEN = 4
NCOL_LEN = 4